### ISSUE TITLE
Context for Translators, strings for Version 1.7

### ISSUE THREAD

**Issue by amenaide** [drwjf/VoiceVista#28]
Hi Jianfeng,

Could you please provide more context for these strings:

114: Both decimal numbers and Google plus codes are supported
150: Current waypoint index: %@ .
276: Latitude or (Latitude, Longitude) or Plus codes
392 Report Beacon Summary

Thank you

**Comment by drwjf** [comment]
When user tap "Input Latitude and Longitude" to input an address, there will be a dialog box, it includes two text fields, user can input latitude into a text field, and longitude into another text field. And user can input Latitude,Longitude into the first field too, or paste Google plus codes from Google Maps into the first field.

> 114: Both decimal numbers and Google plus codes are supported
This is hint for textfield when user input "Latitude or (Latitude, Longitude) or Plus codes"
> 276: Latitude or (Latitude, Longitude) or Plus codes
This is placeholder for textfield when user input "Latitude or (Latitude, Longitude) or Plus codes"




> 150: Current waypoint index: %@ .
> 392 Report Beacon Summary
When user tap "Report Beacon Summary" button in the second tab "Assistant", the VoiceVista will report detail information of the current guiding route. and it includes information about the current target waypoint number of the total waypoints number.
